export const mockProjects = [
  {
    id: 1,
    location: 'San Francisco, CA',
    project_type: 'Residential',
    project_size: 2500,
    timeline: 180,
    material_specs: 'High-end finishes',
    labor_type: 'Union',
    cost: 750000,
    created_at: '2024-03-01',
  },
  {
    id: 2,
    location: 'Los Angeles, CA',
    project_type: 'Commercial',
    project_size: 5000,
    timeline: 240,
    material_specs: 'Standard commercial grade',
    labor_type: 'Non-Union',
    cost: 1200000,
    created_at: '2024-03-15',
  },
  {
    id: 3,
    location: 'San Diego, CA',
    project_type: 'Industrial',
    project_size: 10000,
    timeline: 365,
    material_specs: 'Heavy-duty industrial',
    labor_type: 'Union',
    cost: 2500000,
    created_at: '2024-03-20',
  },
  {
    id: 4,
    location: 'New York, NY',
    project_type: 'Commercial',
    project_size: 7500,
    timeline: 300,
    material_specs: 'Standard commercial grade',
    labor_type: 'Union',
    cost: 1800000,
    created_at: '2024-03-25',
  },
  {
    id: 5,
    location: 'Chicago, IL',
    project_type: 'Industrial',
    project_size: 15000,
    timeline: 420,
    material_specs: 'Heavy-duty industrial',
    labor_type: 'Union',
    cost: 3500000,
    created_at: '2024-03-28',
  },
  {
    id: 6,
    location: 'Houston, TX',
    project_type: 'Commercial',
    project_size: 8000,
    timeline: 270,
    material_specs: 'Standard commercial grade',
    labor_type: 'Non-Union',
    cost: 1600000,
    created_at: '2024-03-30',
  },
  {
    id: 7,
    location: 'Phoenix, AZ',
    project_type: 'Residential',
    project_size: 3000,
    timeline: 210,
    material_specs: 'Standard',
    labor_type: 'Non-Union',
    cost: 450000,
    created_at: '2024-03-31',
  },
  {
    id: 8,
    location: 'Seattle, WA',
    project_type: 'Residential',
    project_size: 2800,
    timeline: 195,
    material_specs: 'High-end finishes',
    labor_type: 'Union',
    cost: 850000,
    created_at: '2024-03-31',
  }
]; 